// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package model

// HighPriorityStats 高优先级请求统计（Priority≥3）
type HighPriorityStats struct {
	// BatchRWCount 批量操作高优先级请求数
	BatchRWCount int64 `json:"batchRWCount"`

	// Percentage 高优先级请求占比（%）
	Percentage float32 `json:"percentage"`

	// QueryCount 查询操作高优先级请求数
	QueryCount int64 `json:"queryCount"`

	// SensorDataCount 传感器数据上报高优先级请求数
	SensorDataCount int64 `json:"sensorDataCount"`

	// SensorRWCount 传感器读写操作高优先级请求数
	SensorRWCount int64 `json:"sensorRWCount"`

	// TotalCount 高优先级请求总数
	TotalCount int64 `json:"totalCount"`
}

// LatencyAnalysis 延迟分析
type LatencyAnalysis struct {
	// BatchRW 延迟分布统计
	BatchRW LatencyDistribution `json:"batchRW"`

	// Query 延迟分布统计
	Query LatencyDistribution `json:"query"`

	// SensorData 延迟分布统计
	SensorData LatencyDistribution `json:"sensorData"`

	// SensorRW 延迟分布统计
	SensorRW LatencyDistribution `json:"sensorRW"`
}

// LatencyDistribution 延迟分布统计
type LatencyDistribution struct {
	// Avg 平均延迟（ms）
	Avg float32 `json:"avg"`

	// Buckets 延迟分布桶计数，对应 [1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000]ms 及 >5000ms
	Buckets []int64 `json:"buckets"`

	// HighPriorityAvg 高优先级平均延迟（ms）
	HighPriorityAvg *float32 `json:"highPriorityAvg,omitempty"`

	// HighPriorityBuckets 高优先级延迟分布桶计数，对应 [1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000]ms 及 >5000ms
	HighPriorityBuckets *[]int64 `json:"highPriorityBuckets,omitempty"`

	// HighPriorityCount 高优先级请求数量
	HighPriorityCount *int64 `json:"highPriorityCount,omitempty"`

	// HighPriorityMax 高优先级最大延迟（ms）
	HighPriorityMax *float32 `json:"highPriorityMax,omitempty"`

	// HighPriorityMin 高优先级最小延迟（ms）
	HighPriorityMin *float32 `json:"highPriorityMin,omitempty"`

	// Max 最大延迟（ms）
	Max float32 `json:"max"`

	// Min 最小延迟（ms）
	Min float32 `json:"min"`
}

// OperationStat 单个操作类型的统计
type OperationStat struct {
	// Errors 错误数量
	Errors int64 `json:"errors"`

	// Operations 操作数量
	Operations int64 `json:"operations"`
}

// OperationsStats 各类操作统计
type OperationsStats struct {
	// BatchRW 单个操作类型的统计
	BatchRW OperationStat `json:"batchRW"`

	// Query 单个操作类型的统计
	Query OperationStat `json:"query"`

	// SensorData 单个操作类型的统计
	SensorData OperationStat `json:"sensorData"`

	// SensorRW 单个操作类型的统计
	SensorRW OperationStat `json:"sensorRW"`
}

// PerformanceMetrics 性能指标
type PerformanceMetrics struct {
	// AvgCompletedQPS 平均完成 QPS
	AvgCompletedQPS float32 `json:"avgCompletedQPS"`

	// AvgSentQPS 平均发送 QPS
	AvgSentQPS float32 `json:"avgSentQPS"`

	// ErrorRate 错误率（%）
	ErrorRate float32 `json:"errorRate"`
}

// StatsReport 最终统计报告
type StatsReport struct {
	// HighPriorityStats 高优先级请求统计（Priority≥3）
	HighPriorityStats *HighPriorityStats `json:"highPriorityStats,omitempty"`

	// LatencyAnalysis 延迟分析
	LatencyAnalysis LatencyAnalysis `json:"latencyAnalysis"`

	// Operations 各类操作统计
	Operations OperationsStats `json:"operations"`

	// Pending 待处理请求数
	Pending int64 `json:"pending"`

	// PerformanceMetrics 性能指标
	PerformanceMetrics PerformanceMetrics `json:"performanceMetrics"`

	// TotalElapsed 总运行时间（秒）
	TotalElapsed float32 `json:"totalElapsed"`

	// TotalErrors 总错误数
	TotalErrors int64 `json:"totalErrors"`

	// TotalOps 完成请求数
	TotalOps int64 `json:"totalOps"`

	// TotalSaveDelayErrors 总因为发现落盘时间超时而产生的错误数
	TotalSaveDelayErrors int64 `json:"totalSaveDelayErrors"`

	// TotalSent 发送请求数
	TotalSent int64 `json:"totalSent"`
}
